### ISSUE TITLE
Issues on Mac ARM

### ISSUE THREAD

**Issue by wrabit** [QiuYannnn/Local-File-Organizer#1]
1. Needed to manual install `matplotlib`
2. Upon running `python main.py`

```bash
$ python main.py
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib_utils.py", line 69, in load_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib, 0x0006): tried: '/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib' (no such file), '/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/will/Code/Local-File-Organizer/main.py", line 13, in <module>
    from data_processing import (
  File "/Users/will/Code/Local-File-Organizer/data_processing.py", line 3, in <module>
    from nexa.gguf import NexaVLMInference, NexaTextInference
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/__init__.py", line 3, in <module>
    from .nexa_inference_vlm import NexaVLMInference
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/nexa_inference_vlm.py", line 22, in <module>
    from nexa.gguf.llama.llama_chat_format import (
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/llama/llama_chat_format.py", line 31, in <module>
    import nexa.gguf.llama.llama as llama
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/llama/llama.py", line 33, in <module>
    from nexa.gguf.llama.llama_grammar import LlamaGrammar
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/llama/llama_grammar.py", line 21, in <module>
    import nexa.gguf.llama.llama_cpp as llama_cpp
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/llama/llama_cpp.py", line 28, in <module>
    _lib = load_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib_utils.py", line 71, in load_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib': dlopen(/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib, 0x0006): tried: '/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib' (no such file), '/Users/will/miniconda/envs/web-ui/local_file_organizer/lib/python3.12/site-packages/nexa/gguf/lib/libllama.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by QiuYannnn** [comment]
Apologies for the late response. Could you provide the info of your laptop? It’s possible that the prebuilt wheel installation failed or that the Nexa SDK wasn’t set up correctly on the machine. You can follow the SDK installation instructions from the official documentation here: [Nexa SDK Installation](https://github.com/NexaAI/nexa-sdk?tab=readme-ov-file#installation).
