### ISSUE TITLE
Requested tokens (2162) exceed context window of 2048

### ISSUE THREAD

**Issue by Ysf101** [QiuYannnn/Local-File-Organizer#18]
Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\Local-File-Organizer-main\Local-File-Organizer-main\main.py", line 337, in <module>
    main()
  File "C:\Users\Lenovo\Downloads\Local-File-Organizer-main\Local-File-Organizer-main\main.py", line 252, in main
    data_texts = process_text_files(text_tuples, text_inference, silent=silent_mode, log_file=log_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Local-File-Organizer-main\Local-File-Organizer-main\text_data_processing.py", line 60, in process_text_files
    data = process_single_text_file(args, text_inference, silent=silent, log_file=log_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Local-File-Organizer-main\Local-File-Organizer-main\text_data_processing.py", line 37, in process_single_text_file
    foldername, filename, description = generate_text_metadata(text, file_path, progress, task_id, text_inference)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Local-File-Organizer-main\Local-File-Organizer-main\text_data_processing.py", line 93, in generate_text_metadata
    filename_response = text_inference.create_completion(filename_prompt)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\envs\local_file_organizer\Lib\site-packages\nexa\gguf\nexa_inference_text.py", line 234, in create_completion
    return self.model.create_completion(prompt=prompt, temperature=temperature, max_tokens=max_tokens, top_k=top_k, top_p=top_p, echo=echo, stream=stream, stop=stop, logprobs=logprobs, top_logprobs=top_logprobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\envs\local_file_organizer\Lib\site-packages\nexa\gguf\llama\llama.py", line 1748, in create_completion
    completion: Completion = next(completion_or_chunks)  # type: ignore
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\envs\local_file_organizer\Lib\site-packages\nexa\gguf\llama\llama.py", line 1191, in _create_completion
    raise ValueError(
ValueError: Requested tokens (2162) exceed context window of 2048

**Comment by QiuYannnn** [comment]
Sorry for late response, you can try to modify the context window to avoid the problem. [link](https://github.com/QiuYannnn/Local-File-Organizer/blob/main/main.py#L73)

**Comment by sindbadsailor** [comment]
I am on Mac M2 and it is working, I am mainly trying to use it to organize a pdf ebook library, but as soon as I put more than 10 pdf files in a folder I get the "Requested tokens (2162) exceed context window of 2048" error, i have already tried your fix to modify the context window, but the problem persists.
is it possible to set a n_ctx greater than 2048 ?
Any ideas?

Is it possible to set it so that only directory structure gets changed but filenames remain the same?

How can I check if Nexa SDK ️is using CPU or GPU Version?

Will there be epub support in the future?
