### ISSUE TITLE
Requested tokens exceed context window 

### ISSUE THREAD

**Issue by re3me** [QiuYannnn/Local-File-Organizer#7]
Hello, 

When trying to execute the program I am receiving the following output - I tried to increase the max_tokens in data_processing.py but I am still stuck here. 

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Participant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Participant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Portable Programs\Organizer\Local-File-Organizer\data_processing.py", line 219, in process_single_text_file
    foldername, filename, description = generate_text_metadata(text)
  File "C:\Portable Programs\Organizer\Local-File-Organizer\data_processing.py", line 170, in generate_text_metadata
    description = summarize_text_content(input_text)
  File "C:\Portable Programs\Organizer\Local-File-Organizer\data_processing.py", line 161, in summarize_text_content
    response = text_inference.create_completion(prompt)
  File "C:\Users\Participant\AppData\Local\Programs\Python\Python310\lib\site-packages\nexa\gguf\nexa_inference_text.py", line 234, in create_completion
    return self.model.create_completion(prompt=prompt, temperature=temperature, max_tokens=max_tokens, top_k=top_k, top_p=top_p, echo=echo, stream=stream, stop=stop, logprobs=logprobs, top_logprobs=top_logprobs)
  File "C:\Users\Participant\AppData\Local\Programs\Python\Python310\lib\site-packages\nexa\gguf\llama\llama.py", line 1748, in create_completion
    completion: Completion = next(completion_or_chunks)  # type: ignore
  File "C:\Users\Participant\AppData\Local\Programs\Python\Python310\lib\site-packages\nexa\gguf\llama\llama.py", line 1191, in _create_completion
    raise ValueError(
ValueError: Requested tokens (3362) exceed context window of 2048
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Portable Programs\Organizer\Local-File-Organizer\main.py", line 99, in <module>
    main()
  File "C:\Portable Programs\Organizer\Local-File-Organizer\main.py", line 80, in main
    data_texts = process_text_files(text_tuples)
  File "C:\Portable Programs\Organizer\Local-File-Organizer\data_processing.py", line 235, in process_text_files
    results = pool.map(process_single_text_file, text_tuples)
  File "C:\Users\Participant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Participant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
ValueError: Requested tokens (3362) exceed context window of 2048

**Comment by QiuYannnn** [comment]
Thank you for your sharing!

The default context window size for text_inference is 2048 tokens and uses a sliding window mechanism to preserve the conversation history from previous rounds. Currently, there is no option to customize the context window size, but this feature could be introduced in future updates.

Feel free to let me know if you need any further adjustments!

**Comment by d1maz** [comment]
It looks like this feature, in the Nexa SDK, is coming in the next release.

You can read about it here: https://github.com/NexaAI/nexa-sdk/issues/109

**Comment by re3me** [comment]
How do I use this when this error occurs? Are my files too large? Sorry I dont understand the issue.

**Comment by sindbadsailor** [comment]
> How do I use this when this error occurs? Are my files too large? Sorry I dont understand the issue.

I have the same issue

**Comment by rop79** [comment]
the project sounds very promising, but I'm facing the same issue and don't know how to resolve it.

**Comment by QiuYannnn** [comment]
Sorry for late response, you can try to modify the context window to avoid the problem. [link](https://github.com/QiuYannnn/Local-File-Organizer/blob/main/main.py#L73)
